### ISSUE TITLE
BUG: load_direction.name - AttributeError: 'int' object has no attribute 'name'

### ISSUE THREAD

**Issue by and-ratajski** [Dlubal-Software/RSTAB_Python_Client#18]
**Describe the bug**
When defining a MemberLoad there is an AttributeError raised as the class MemberLoad tries to read name field from enum (int) variable

**To Reproduce**
Create a sample construction with member loads, I used an example from https://github.com/Dlubal-Software/RFEM_Python_Client/blob/main/Examples/SteelDesign/SteelDesignExcel.py and changed it a little bit to work with RSTAB & no Excel

**Expected behavior**
MemberLoads get added without errors.

**Screenshots**
Possible bug:
https://github.com/Dlubal-Software/RSTAB_Python_Client/blob/184a5d3fd4bd2c0a2053798b4adff328d612822a/RSTAB/Loads/memberLoad.py#L51-L52

**Desktop (please complete the following information):**
 - Version of WIN10 OS: Microsoft Windows Server 2022 Datacenter
 - Version of RSTAB9: 9.02.0067
 - Version of tool: 1.7.0

**Additional context**
Possibly this issue occurs also in RFEM SDK

**Comment by and-ratajski** [comment]
When needed, I can attach my python script that generates the error.

**Comment by OndraMichal** [comment]
Hi @and-ratajski,
please add the script. I tested MemberLoad running and peaked into the object and I see no problem.
![image](https://github.com/Dlubal-Software/RSTAB_Python_Client/assets/37547309/1018f9ff-e1ff-470d-bc62-f9483d12a5a6)

**Comment by and-ratajski** [comment]
Here's the script I'm trying to have calculated:

[RSTAB_error_eg.py.zip](https://github.com/Dlubal-Software/RSTAB_Python_Client/files/11814879/RSTAB_error_eg.py.zip)

**Comment by OndraMichal** [comment]
You are using **NodalLoadDirection** instead of **MemberLoadDirection**. If you change it and switch **bracing_mat** to 'S355' which is defined in our material database, it works without issues.
[RSTAB_error_eg.zip](https://github.com/Dlubal-Software/RSTAB_Python_Client/files/11815291/RSTAB_error_eg.zip)

**Comment by and-ratajski** [comment]
Ok - thank you! I was mislead by the RFEM example, where the author actually uses **NodalLoadDirection**:

https://github.com/Dlubal-Software/RFEM_Python_Client/blob/6614d4925e1267ba38d88d8d7823acc556842a45/Examples/SteelDesign/SteelDesignExcel.py#L387-L419

Now it all works.
