### ISSUE TITLE
BUG: demo mode just up to 12 members

### ISSUE THREAD

**Issue by scja1991** [Dlubal-Software/RSTAB_Python_Client#29]
**Describe the bug**
When using the command Calculate_all() I get the error message that in demo mode just up to 12 members can be calculated.

**To Reproduce**
I have a mid-size model (around 100 members). When I use the command Calculate_all() I get the discribed error message. When I calculate everything explicitly with CalculateSelectedCases() everything is fine.

**Expected behavior**
I expect that all load cases, load combinations, adons etc. will be calculated.

 - Version of WIN11 Pro
 - Version of RSTAB9.03.0007
 - Version of tool v1.08.0

**Additional context**

**Comment by OndraMichal** [comment]
Hi @scja1991,
we need more info to assess the situation. What type of license do you have? Are you sure you din't switch to demo? Can you share the model so we can test the calculation?

**Comment by scja1991** [comment]
I am sure, that i have not switched to demo. I have a licence for RSTAB 9, Stress-Strain Analysis, Steel Design and Timber Design.
The RSTAB Model and my Python-Code are attached.
[RSTAB_test.zip](https://github.com/Dlubal-Software/RSTAB_Python_Client/files/12734524/RSTAB_test.zip)

**Comment by Sacek073** [comment]
Hello @scja1991. I tested this and I can't reproduce this error. Can you please verify, that this error still persisit in your system? 
Tested on: RSTAB version: 9.04.007, tool verison 1.09.1. I opened your model and ran the attached script without any errors. Please get back to us, so we can figure this out. Thank you
