### ISSUE TITLE
BUG: `CalculateSelectedCases()` raises Attribute Error

### ISSUE THREAD

**Issue by scja1991** [Dlubal-Software/RSTAB_Python_Client#31]
Calculating with `CalculateSelectedCases()` raises Attribute Error.

1. Open the model from the zip below
2. Run the minimal Python-Example script from the zip

![image](https://github.com/Dlubal-Software/RSTAB_Python_Client/assets/129157161/effdce44-9660-40aa-aa0c-b20b62c2658c)

**Desktop (please complete the following information):**
 - Windows 11 Pro for Workstations
 - RSTAB9.04.0004
 - Version of tool 1.8.0
[min_ex.zip](https://github.com/Dlubal-Software/RSTAB_Python_Client/files/13166320/min_ex.zip)

**Comment by Sacek073** [comment]
Hello @scja1991, thank you for reaching out to us. I tested this with RSTAB version 9.04.007 and tool version 1.09.1 and it is working right now. If this still persists in your configuration, please contat us again, thank you.
