### ISSUE TITLE
BUG: CoordinateSystemType, CoordinateSystemRotationAnglesSequence are missing

### ISSUE THREAD

**Issue by damianbobrowski** [Dlubal-Software/RSTAB_Python_Client#34]
**Describe the bug**
Commit
https://github.com/Dlubal-Software/RSTAB_Python_Client/commit/3cc680550d19d5ed5f51deacb583717f12fc3ba0

implements `class CoordinateSystem():`

bellows dependencies are not included in RSATB 1.9.2:

https://github.com/Dlubal-Software/RSTAB_Python_Client/blob/3cc680550d19d5ed5f51deacb583717f12fc3ba0/RSTAB/BasicObjects/coordinateSystem.py#L2

**To Reproduce**
Just search dependency in main branch
https://github.com/search?q=repo%3ADlubal-Software%2FRSTAB_Python_Client%20CoordinateSystemType&type=code

**Comment by OndraMichal** [comment]
Hi @damianbobrowski,
thank you for alerting us. It will be fixed shortly.

**Comment by OndraMichal** [comment]
Fixed
