### ISSUE TITLE
BUG: Hall Example does'n work

### ISSUE THREAD

**Issue by FrankFaulstich** [Dlubal-Software/RSTAB_Python_Client#37]
The hall example does not work with the current version of Python HLF.

**Comment by heetrojivadiya** [comment]
Hey @FrankFaulstich, 
I have tested the hall.py with python 3.11 and RSTAB version 9.06.002 on main branch. It is working fine without giving any errors. May you please explain what kind of errors are you getting with that example?

<img width="596" alt="image" src="https://github.com/Dlubal-Software/RSTAB_Python_Client/assets/108512789/864e335c-2b5c-46ec-a46d-dd36f13cc28a">

<img width="628" alt="image" src="https://github.com/Dlubal-Software/RSTAB_Python_Client/assets/108512789/e2cfd7cc-99e0-4c7a-b3f7-0bd7afc3784f">

**Comment by heetrojivadiya** [comment]
Tested and issue not found.
